blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    PostListView,
    PostDeleteView,
    PostCreateView,
    PostUpdateView,
    PostDetailView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", PostListView.as_view(), name="posts_list"),
    path("create/", PostCreateView.as_view(), name="posts_create"),
    path("<int:pk>/", PostDetailView.as_view(), name="posts_detail"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="posts_update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="posts_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Заголовок",
        help_text="Введите заголовок поста",
    )
    description = models.TextField(
        verbose_name="Содержание",
        help_text="Введите содержание поста",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to="posts/",
        verbose_name="Превью",
        help_text="Вставьте изображение для поста",
        blank=True,
        null=True,
    )
    is_public = models.BooleanField(
        default=True,
        verbose_name="Признак публикации",
        help_text="Укажите, доступен ли пост для просмотра",
    )
    views_counter = models.PositiveIntegerField(
        default=0,
        verbose_name="Количество просмотров",
        help_text="Количество просмотров поста",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Дата и время создания поста",
        editable=False,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата обновления",
        help_text="Дата и время последнего обновления поста",
        editable=False,
    )

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["name"]

    def __str__(self):
        return self.name

blog/forms.py
from django import forms

from blog.models import Post
from config.forms import StyleFormMixin


class PostForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Post
        fields = ["name", "description", "image", "is_public"]

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from blog.forms import PostForm
from blog.models import Post


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(is_public=True)


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy("blog:posts_list")


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_path"] = self.request.path
        return context

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy("blog:posts_list")

    def get_success_url(self):
        return reverse("blog:posts_delete", args=[self.kwargs.get("pk")])


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("blog:posts_list")

blog/templates/blog/includes/post_card.html
{% load my_tags %}

<div class="col">
    <div class="card shadow-sm h-100">
        {% if object.image %}
            <img src="{{ object.image | media_filter }}">
        {% endif %}
        <div class="card-body">
            <h4 class="card-title"> {{ object.name }} </h4>
            <p class="card-text">{{ object.description|slice:100 }}
            <p class="text-body-secondary"> {{ object.created_at }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-primary" href="{% url 'blog:posts_update' object.pk %}" role="button">Изменить</a>
                    <a class="btn btn-primary" href="{% url 'blog:posts_delete' object.pk %}" role="button">Удалить</a>
                    {% url 'blog:posts_detail' object.pk as blog_info_url %}
                    {% if current_path != blog_info_url %}
                        <a class="btn btn-primary" href="{% url 'blog:posts_detail' object.pk %}" role="button">Гладить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>