blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    PostListView,
    PostDeleteView,
    PostCreateView,
    PostUpdateView,
    PostDetailView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", PostListView.as_view(), name="posts_list"),
    path("create/", PostCreateView.as_view(), name="posts_create"),
    path("<int:pk>/", PostDetailView.as_view(), name="posts_detail"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="posts_update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="posts_delete"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="products_list"),
    path("catalogs/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="products_detail"),
    path("catalogs/create", ProductCreateView.as_view(), name="products_create"),
    path("catalogs/<int:pk>/update", ProductUpdateView.as_view(), name="products_update"),
    path("catalogs/<int:pk>/delete", ProductDeleteView.as_view(), name="products_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterUserView
from django.contrib.auth.views import LoginView, LogoutView

app_name = UsersConfig.name

urlpatterns = [
    path("register/", RegisterUserView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Название",
        help_text="Введите название категории",
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
        help_text="Введите наименование товара",
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание товара",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to="products/",
        verbose_name="Изображение",
        blank=True,
        null=True,
        help_text="Загрузите изображение товара",
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена",
        help_text="Введите цену товара",
    )
    is_public = models.BooleanField(
        default=True,
        verbose_name="Признак публикации",
        help_text="Укажите, опубликован ли товар",
    )
    category = models.ForeignKey(
        Category,
        verbose_name="Категория",
        help_text="Выберите категорию для товара",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    owner = models.ForeignKey(
        "users.User",
        verbose_name="Владелец",
        help_text="Укажите владельца товара",
        null=True,
        on_delete=models.SET_NULL,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Дата и время создания товара",
        editable=False,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата обновления",
        help_text="Дата и время последнего обновления",
        editable=False,
    )

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["name"]
        permissions = [
            ("can_unpublish_product", "Может снять товар с публикации"),
            ("can_delete_product", "Может удалить товар"),
        ]

    def __str__(self):
        return self.name

catalog/forms.py
from django.core.exceptions import ValidationError
from django import forms

from catalog.models import Product
from catalog.utils import validate_disallowed_words
from config.forms import StyleFormMixin


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "image", "price", "category", "is_public"]

    def clean_price(self):
        price = self.cleaned_data["price"]
        if int(price) < 0:
            raise ValidationError("Цена не может иметь отрицательное значение")
        return price

    def clean_name(self):
        name = self.cleaned_data["name"]
        validate_disallowed_words(name)
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description", "")
        validate_disallowed_words(description)
        return description


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "is_public",
        ]

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.shortcuts import render
from catalog.forms import ProductForm, ProductModeratorForm
from catalog.models import Product, Category
from services import get_products_from_cache, get_products_by_category


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        return get_products_from_cache().filter(is_public=True)


def products_by_category_view(request, category_id):
    products = get_products_by_category(category_id)
    category = Category.objects.get(id=category_id)
    return render(request, 'catalog/products_by_category.html', {'products': products, 'category': category})


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_path"] = self.request.path
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:products_list")

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:products_list")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.has_perm("catalog.update_product"):
            return ProductForm
        if user.has_perm("catalog.can_unpublish_product") and user.has_perm(
                "catalog.delete_product"
        ):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:products_list")

catalog/templates/catalog/includes/headers.html
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-10 col-md-7 py-4">
                    <h4>About 406</h4>
                    <p class="text-body-secondary">Сегодня свами все умные люди из 406 кабинета из 5 отделения псих больных</p>
                </div>
                <div class="col-sm-2 offset-md-1 py-4">
                    <ul class="list-unstyled">
                        <li>
                            <a class="btn btn-sm btn-outline-secondary" href="{% url 'catalog:products_list' %}"
                               role="button">Главная
                            </a>
                        </li>
                    </ul>
                    {% if user.is_authenticated %}
                        <ul class="list-unstyled">
                            <li>
                                <form action="{% url 'users:logout' %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm btn-outline-secondary">Выйти</button>
                                </form>
                            </li>
                        </ul>
                    {% else %}
                        <ul class="list-unstyled">
                            <li>
                                <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:register' %}"
                                   role="button">Регистрация
                                </a>
                            </li>
                        </ul>
                        <ul class="list-unstyled">
                            <li>
                                <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:login' %}"
                                   role="button">Войти
                                </a>
                            </li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>